spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cotton?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 20  #最小空闲连接，默认值10
      maximum-pool-size: 100  #最大连接数 默认10
      idle-timeout: 30000  #不能小于30秒，否则默认回到1800秒
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000  #空闲超时时间
      connection-test-query: SELECT 1


  spring:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /static/**               #静态资源访问路径
  resources:
    static-locations: classpath:/static/          #静态资源映射路径
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/static/layuimini/
    suffix: .html
server:
  port: 80

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
